package org.iglooproject.wicket.more.link.descriptor.builder.state.parameter.chosen;

import org.iglooproject.wicket.more.link.descriptor.builder.state.parameter.choice.somechosen.ISixOrMoreMappableParameterSomeChosenChoiceState;
import org.iglooproject.wicket.more.link.descriptor.builder.state.parameter.chosen.common.IFiveChosenParameterState;

public interface ISixMappableParameterFiveChosenParameterState<
        InitialState,
        TParam1,
        TParam2,
        TParam3,
        TParam4,
        TParam5,
        TParam6,
        TChosenParam1,
        TChosenParam2,
        TChosenParam3,
        TChosenParam4,
        TChosenParam5,
        TLateTargetDefinitionPageResult,
        TLateTargetDefinitionResourceResult,
        TLateTargetDefinitionImageResourceResult>
    extends IFiveChosenParameterState<
            InitialState,
            TChosenParam1,
            TChosenParam2,
            TChosenParam3,
            TChosenParam4,
            TChosenParam5,
            TLateTargetDefinitionPageResult,
            TLateTargetDefinitionResourceResult,
            TLateTargetDefinitionImageResourceResult>,
        ISixOrMoreMappableParameterSomeChosenChoiceState {

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam1,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andFirst();

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam2,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andSecond();

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam3,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andThird();

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam4,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andFourth();

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam5,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andFifth();

  @Override
  ISixMappableParameterSixChosenParameterState<
          InitialState,
          TParam1,
          TParam2,
          TParam3,
          TParam4,
          TParam5,
          TParam6,
          TChosenParam1,
          TChosenParam2,
          TChosenParam3,
          TChosenParam4,
          TChosenParam5,
          TParam6,
          TLateTargetDefinitionPageResult,
          TLateTargetDefinitionResourceResult,
          TLateTargetDefinitionImageResourceResult>
      andSixth();
}
