-- Hibernate hbm2ddl script
create sequence StorageConsistencyCheck_id_seq start with 1 increment by 1;
create sequence StorageFailure_id_seq start with 1 increment by 1;
create table Fichier (id bigint not null, checksum text not null, checksumType varchar(255) not null check (checksumType in ('SHA_256','NONE')), createdBy_id bigint, createdBy_type varchar(255), creationDate timestamp(6) not null, filename text not null, invalidationDate timestamp(6), mimetype text not null, relativePath text not null, size bigint not null, status varchar(255) not null check (status in ('TRANSIENT','ALIVE','INVALIDATED','UNAVAILABLE')), type varchar(255) not null, uuid uuid not null unique, validationDate timestamp(6), storageUnit_id bigint not null, primary key (id));
create table StorageConsistencyCheck (id bigint not null, checkFinishedOn timestamp(6) not null, checkStartedOn timestamp(6) not null, checkType varchar(255) check (checkType in ('NONE','LISTING_SIZE','LISTING_SIZE_CHECKSUM')), checksumMismatchCount integer, dbFichierCount integer, dbFichierSize bigint, fsFileCount integer, fsFileSize bigint, missingFichierCount integer, missingFileCount integer, sizeMismatchCount integer, status varchar(255) check (status in ('OK','FAILED')), storageUnit_id bigint, primary key (id));
create table StorageFailure (id bigint not null, acknowledgedOn timestamp(6), creationTime timestamp(6) not null, fixedOn timestamp(6), lastFailureOn timestamp(6) not null, path varchar(255) not null unique, status varchar(255) not null check (status in ('ALIVE','FIXED','ACKNOWLEDGED')), type varchar(255) not null check (type in ('MISSING_FILE','MISSING_ENTITY','SIZE_MISMATCH','CHECKSUM_MISMATCH')), consistencyCheck_id bigint not null, fichier_id bigint, primary key (id));
create table StorageUnit (id bigint not null, checkChecksumDelay numeric(21,0), checkDelay numeric(21,0), checkType varchar(255) not null check (checkType in ('NONE','LISTING_SIZE','LISTING_SIZE_CHECKSUM')), creationDate timestamp(6) not null, path varchar(255) not null unique, splitDuration numeric(21,0), splitSize bigint, status varchar(255) not null check (status in ('ALIVE','ARCHIVED')), type varchar(255) not null, primary key (id));
alter table if exists Fichier add constraint FKpa97cl0evjqh8xllabrn674sw foreign key (storageUnit_id) references StorageUnit;
alter table if exists StorageConsistencyCheck add constraint FK5e6p4tl92klsxnopvqll8cm3t foreign key (storageUnit_id) references StorageUnit;
alter table if exists StorageFailure add constraint FKq2amgua4uychn1qjr2j5ss7hq foreign key (consistencyCheck_id) references StorageConsistencyCheck;
alter table if exists StorageFailure add constraint FKldqr5ukxawf4ifga3rf5hlr3r foreign key (fichier_id) references Fichier;

-- Hibernate hbm2ddl script (end)